import { RoadmapPhaseInfo } from '../types/health';

export const APP_METADATA = {
  name: 'Secure Military Communication Using Caesar Cipher',
  shortTitle: 'Caesar Command',
  version: '1.0.0-phase9',
  phase: 'PHASE 9 // Progressive Web App (PWA) & Offline Shell',
  academicNotice: 'ACADEMIC CRYPTOGRAPHY DEMONSTRATION ONLY: Caesar Cipher is an ancient classical substitution cipher (keyspace = 26) with zero computational security against modern cryptanalysis. Not for production or military use.',
  classification: 'UNCLASSIFIED // ACADEMIC DEMO',
  license: 'Educational / Research Only',
};

export const SYSTEM_PHASES: RoadmapPhaseInfo[] = [
  {
    id: 'p0',
    code: 'PHASE 0',
    title: 'Requirements & Architecture',
    description: 'System specification, data flow, API boundaries, and threat model',
    status: 'completed',
    category: 'Foundation',
  },
  {
    id: 'p1',
    code: 'PHASE 1',
    title: 'Project Foundation',
    description: 'Folder structure, TypeScript types, health status dashboard, FastAPI backend skeleton',
    status: 'completed',
    category: 'Foundation',
  },
  {
    id: 'p2',
    code: 'PHASE 2',
    title: 'Caesar Cipher Engine',
    description: 'Pure mathematical cipher core, Shift (0-25), letter frequency analysis',
    status: 'completed',
    category: 'Crypto Core',
  },
  {
    id: 'p3',
    code: 'PHASE 3',
    title: 'Web UI Scaffolding',
    description: 'Tactical command dashboard, responsive military console components',
    status: 'completed',
    category: 'User Interface',
  },
  {
    id: 'p4',
    code: 'PHASE 4',
    title: 'Encrypt/Decrypt Workflow',
    description: 'Fully connected Caesar cipher encryption and decryption workflows with input/shift validation, error handling, edge-case preservation, and clipboard copying',
    status: 'completed',
    category: 'User Interface',
  },
  {
    id: 'p5',
    code: 'PHASE 5',
    title: 'Operations Dashboard',
    description: 'Telemetry analytics, total operation metrics, active shift dial, quick encrypt/decrypt actions, and local session audit log',
    status: 'completed',
    category: 'User Interface',
  },
  {
    id: 'p6',
    code: 'PHASE 6',
    title: 'Authentication & Security',
    description: 'FastAPI auth endpoints (/auth/register, /auth/login, /auth/me), PBKDF2 salted password hashing, stateless HMAC-SHA256 JWT tokens, and React auth state management',
    status: 'completed',
    category: 'Security & Auth',
  },
  {
    id: 'p7',
    code: 'PHASE 7',
    title: 'Message History & Vault',
    description: 'Authenticated message vault (GET /messages, GET /messages/{id}, DELETE /messages/{id}), strict user isolation, search, sort, copy, delete, and zero-plaintext storage',
    status: 'completed',
    category: 'Security & Auth',
  },
  {
    id: 'p8',
    code: 'PHASE 8',
    title: 'Brute-Force Attack Demo',
    description: 'Educational keyspace exhaustion generating all 26 shifts, candidate plaintext heuristic scoring, interactive attack visualization, and local-first execution',
    status: 'completed',
    category: 'Crypto Core',
  },
  {
    id: 'p9',
    code: 'PHASE 9',
    title: 'PWA & Offline Support',
    description: 'Web App Manifest, custom icons, service worker offline shell, airgap execution, offline encryption/decryption/brute-force, and installability',
    status: 'completed',
    category: 'Platform',
  },
  {
    id: 'p10',
    code: 'PHASE 10',
    title: 'Backend REST API',
    description: 'FastAPI endpoints for authentication, message vault, and metrics',
    status: 'upcoming',
    category: 'Integration',
  },
  {
    id: 'p11',
    code: 'PHASE 11',
    title: 'Database Persistence',
    description: 'PostgreSQL database schemas, migrations, and ORM models',
    status: 'upcoming',
    category: 'Integration',
  },
  {
    id: 'p12',
    code: 'PHASE 12',
    title: 'Frontend-Backend Sync',
    description: 'Full REST API integration with graceful offline fallback',
    status: 'upcoming',
    category: 'Integration',
  },
  {
    id: 'p13',
    code: 'PHASE 13',
    title: 'Security & Validation',
    description: 'Input whitelisting, rate limiting, and zero-leakage verification',
    status: 'upcoming',
    category: 'Security & Auth',
  },
  {
    id: 'p14',
    code: 'PHASE 14',
    title: 'Comprehensive Testing',
    description: 'Automated unit tests, integration test suite, cipher fuzzing',
    status: 'upcoming',
    category: 'Foundation',
  },
  {
    id: 'p15',
    code: 'PHASE 15',
    title: 'Web Deployment',
    description: 'Vercel / Cloud Run production deployment workflow',
    status: 'upcoming',
    category: 'Platform',
  },
  {
    id: 'p16',
    code: 'PHASE 16',
    title: 'Android Conversion',
    description: 'Capacitor native shell, AndroidManifest, mobile responsive viewport',
    status: 'upcoming',
    category: 'Platform',
  },
  {
    id: 'p17',
    code: 'PHASE 17',
    title: 'Android Mobile Testing',
    description: 'Touch dial ergonomics, offline storage on mobile, safe-area insets',
    status: 'upcoming',
    category: 'Platform',
  },
  {
    id: 'p18',
    code: 'PHASE 18',
    title: 'Release Packaging',
    description: 'Build artifacts, APK generation, distribution assets',
    status: 'upcoming',
    category: 'Platform',
  },
  {
    id: 'p19',
    code: 'PHASE 19',
    title: 'Academic Documentation',
    description: 'Research report, mathematical proofs, vulnerability dissertation',
    status: 'upcoming',
    category: 'Foundation',
  },
];
